"""
Data Models for CurricuAlign AI LLM Technology Intelligence Engine.
"""

import datetime
import os
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class TechnologyCategories(BaseModel):
    """
    Structured 18 technology categories explicitly extracted from job postings.
    """
    languages: List[str] = Field(default_factory=list, description="Programming Languages (e.g. Python, Java, C++)")
    frameworks: List[str] = Field(default_factory=list, description="Frameworks (e.g. FastAPI, Spring Boot, React)")
    libraries: List[str] = Field(default_factory=list, description="Libraries (e.g. Pandas, NumPy, Scikit-learn)")
    databases: List[str] = Field(default_factory=list, description="Databases (e.g. PostgreSQL, Redis, MongoDB)")
    cloud: List[str] = Field(default_factory=list, description="Cloud Platforms (e.g. AWS, GCP, Azure)")
    devops: List[str] = Field(default_factory=list, description="DevOps Tools (e.g. Docker, Kubernetes, Jenkins)")
    ai: List[str] = Field(default_factory=list, description="AI / ML Frameworks (e.g. PyTorch, TensorFlow)")
    vector_databases: List[str] = Field(default_factory=list, description="Vector Databases (e.g. ChromaDB, Pinecone, Qdrant)")
    llm_frameworks: List[str] = Field(default_factory=list, description="LLM Frameworks (e.g. LangChain, LlamaIndex, vLLM)")
    agent_frameworks: List[str] = Field(default_factory=list, description="Agent Frameworks (e.g. CrewAI, AutoGen)")
    operating_systems: List[str] = Field(default_factory=list, description="Operating Systems (e.g. Linux, Ubuntu, Windows)")
    developer_tools: List[str] = Field(default_factory=list, description="Developer Tools (e.g. VS Code, Postman, Webpack)")
    version_control: List[str] = Field(default_factory=list, description="Version Control (e.g. Git, GitHub, GitLab)")
    message_brokers: List[str] = Field(default_factory=list, description="Message Brokers (e.g. Apache Kafka, RabbitMQ)")
    container_technologies: List[str] = Field(default_factory=list, description="Container Technologies (e.g. Docker, Podman)")
    infrastructure_tools: List[str] = Field(default_factory=list, description="Infrastructure Tools (e.g. Terraform, Ansible)")
    monitoring_tools: List[str] = Field(default_factory=list, description="Monitoring Tools (e.g. Prometheus, Grafana, Datadog)")
    testing_frameworks: List[str] = Field(default_factory=list, description="Testing Frameworks (e.g. PyTest, JUnit, Cypress)")

    class Config:
        frozen = False


class LLMExecutionStats(BaseModel):
    """
    Execution and telemetry stats for LLM extraction requests.
    """
    prompt_tokens: int = Field(default=0, description="Token count in the prompt sent to Gemini.")
    completion_tokens: int = Field(default=0, description="Token count in the response generated by Gemini.")
    total_tokens: int = Field(default=0, description="Total tokens used.")
    latency_ms: float = Field(default=0.0, description="Latency of the LLM call in milliseconds.")
    retry_count: int = Field(default=0, description="Number of retries executed.")
    cache_hit: bool = Field(default=False, description="Whether the request was served from cache.")


class LLMConfig(BaseModel):
    """
    Configuration parameters for Gemini LLM requests.
    """
    model_name: str = Field(default_factory=lambda: os.getenv("GEMINI_MODEL", "gemini-2.5-flash"))
    temperature: float = Field(default=0.0, description="Temperature setting for LLM extraction (0.0 for deterministic extraction).")
    max_tokens: int = Field(default=2048, description="Maximum token length for generated response.")
    retry_count: int = Field(default=3, description="Maximum retry attempts on API errors or rate limits.")
    timeout: float = Field(default=30.0, description="Request timeout in seconds.")
    api_key: Optional[str] = Field(default_factory=lambda: os.getenv("GEMINI_API_KEY", ""))


class TechnologyExtraction(BaseModel):
    """
    Structured Technology Intelligence Result for a job posting.
    """
    job_id: str = Field(..., description="Unique job identifier.")
    technologies: TechnologyCategories = Field(..., description="Categorized technology intelligence.")
    extraction_timestamp: str = Field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat(),
        description="Timestamp when extraction occurred."
    )
    stats: Optional[LLMExecutionStats] = Field(default=None, description="LLM execution telemetry and statistics.")

    class Config:
        frozen = False
