import { UnifiedAnalysisResult, DashboardSummary, StatusSummary, HealthCheckResult, KnowledgeGraphData } from '../types/api';

export const MOCK_ANALYSIS_RESULT: UnifiedAnalysisResult = {
  analysis_id: 'analysis_demo_2026_0802',
  document_id: 'doc_cs_curriculum_v4',
  university_name: 'Stanford University School of Engineering',
  curriculum_year: '2025-2026',
  department: 'Department of Computer Science',
  alignment_score: 72.8,
  covered_skills: [
    {
      id: 'cov-1',
      academic_skill: 'Data Structures & Algorithms',
      matched_industry_skill: 'Data Structures & Algorithmic Problem Solving',
      similarity: 96.5,
      priority: 'LOW',
      status: 'COVERED',
      category: 'Computer Science Core',
      industry_demand_score: 95,
      industry_importance_score: 98,
      trend: 'STABLE',
      academic_evidence: 'CS106B: Arrays, Linked Lists, Trees, Graphs, Hashing, Time/Space Complexity O(N).',
      industry_evidence: 'Required in 94% of Senior Software Engineering job descriptions.',
    },
    {
      id: 'cov-2',
      academic_skill: 'Object-Oriented Programming (Java/C++)',
      matched_industry_skill: 'Object-Oriented Software Design',
      similarity: 92.0,
      priority: 'LOW',
      status: 'COVERED',
      category: 'Software Engineering',
      industry_demand_score: 88,
      industry_importance_score: 90,
      trend: 'STABLE',
      academic_evidence: 'CS108: Object-Oriented System Design, Inheritance, Polymorphism, Design Patterns.',
      industry_evidence: 'Core requirement for enterprise applications and scalable microservices.',
    },
    {
      id: 'cov-3',
      academic_skill: 'Operating Systems & Concurrency',
      matched_industry_skill: 'Systems Programming & Multi-threading',
      similarity: 88.4,
      priority: 'LOW',
      status: 'COVERED',
      category: 'Systems & Infrastructure',
      industry_demand_score: 82,
      industry_importance_score: 85,
      trend: 'STABLE',
      academic_evidence: 'CS110: Process Management, Threads, Deadlocks, Virtual Memory, I/O Subsystems.',
      industry_evidence: 'Vital for cloud infrastructure engineers and low-latency systems development.',
    },
    {
      id: 'cov-4',
      academic_skill: 'Relational Database Management (SQL)',
      matched_industry_skill: 'Relational Database Design & SQL Querying',
      similarity: 91.2,
      priority: 'LOW',
      status: 'COVERED',
      category: 'Data Management',
      industry_demand_score: 92,
      industry_importance_score: 91,
      trend: 'STABLE',
      academic_evidence: 'CS145: Relational Algebra, SQL, Normalization (3NF/BCNF), Indexing, ACID Transactions.',
      industry_evidence: 'Essential for data engineers, backend developers, and data architects.',
    },
  ],
  partial_skills: [
    {
      id: 'part-1',
      academic_skill: 'Introduction to Machine Learning',
      matched_industry_skill: 'Production MLOps & LLM Orchestration',
      similarity: 64.5,
      priority: 'HIGH',
      status: 'PARTIAL',
      category: 'AI & Data Science',
      industry_demand_score: 96,
      industry_importance_score: 95,
      trend: 'RISING',
      academic_evidence: 'CS229: Supervised Learning, Linear Regression, SVMs, Basic Neural Networks in Python.',
      industry_evidence: 'Industry demands production model deployment, LangChain, RAG, vector databases, and MLOps tools.',
    },
    {
      id: 'part-2',
      academic_skill: 'Computer Networking Basics',
      matched_industry_skill: 'Cloud Networking, Service Meshes & gRPC',
      similarity: 58.0,
      priority: 'MEDIUM',
      status: 'PARTIAL',
      category: 'Systems & Infrastructure',
      industry_demand_score: 85,
      industry_importance_score: 82,
      trend: 'RISING',
      academic_evidence: 'CS144: TCP/IP stack, Socket programming, HTTP/1.1 protocols.',
      industry_evidence: 'Industry emphasizes Kubernetes networking, Istio service mesh, gRPC, and HTTP/3.',
    },
    {
      id: 'part-3',
      academic_skill: 'Web Applications Development',
      matched_industry_skill: 'Modern React 19, TypeScript & Micro-frontends',
      similarity: 61.2,
      priority: 'HIGH',
      status: 'PARTIAL',
      category: 'Web & Cloud',
      industry_demand_score: 94,
      industry_importance_score: 92,
      trend: 'RISING',
      academic_evidence: 'CS193: Basic HTML/JS, DOM manipulation, simple Node.js backend API.',
      industry_evidence: 'Modern software engineering expects Next.js 15, React Server Components, TypeScript, and state management.',
    },
  ],
  gap_skills: [
    {
      id: 'gap-1',
      academic_skill: 'Not Taught in Syllabus',
      matched_industry_skill: 'Containerization & Orchestration (Docker & Kubernetes)',
      similarity: 12.0,
      priority: 'CRITICAL',
      status: 'GAP',
      category: 'DevOps & Cloud Engineering',
      industry_demand_score: 98,
      industry_importance_score: 99,
      trend: 'RISING',
      academic_evidence: 'No mention of Docker, container images, Helm charts, or Kubernetes in current course syllabi.',
      industry_evidence: 'Found in 89% of modern Cloud Engineering, DevOps, and Backend Developer postings.',
    },
    {
      id: 'gap-2',
      academic_skill: 'Not Taught in Syllabus',
      matched_industry_skill: 'Vector Databases & Retrieval Augmented Generation (RAG)',
      similarity: 8.5,
      priority: 'CRITICAL',
      status: 'GAP',
      category: 'AI & Data Science',
      industry_demand_score: 97,
      industry_importance_score: 96,
      trend: 'RISING',
      academic_evidence: 'Missing coverage on Pinecone, Qdrant, Milvus, hybrid search, embeddings, and RAG architectures.',
      industry_evidence: 'High-growth hiring category for AI Engineers and Applied ML Researchers in 2025-2026.',
    },
    {
      id: 'gap-3',
      academic_skill: 'Not Taught in Syllabus',
      matched_industry_skill: 'CI/CD Pipelines & Automated Infrastructure (Terraform & GitHub Actions)',
      similarity: 15.4,
      priority: 'HIGH',
      status: 'GAP',
      category: 'DevOps & Cloud Engineering',
      industry_demand_score: 91,
      industry_importance_score: 89,
      trend: 'RISING',
      academic_evidence: 'Missing practical hands-on exercises with GitHub Actions, GitOps, and Infrastructure as Code (IaC).',
      industry_evidence: 'Critical requirement for automated software delivery and cloud release management.',
    },
    {
      id: 'gap-4',
      academic_skill: 'Not Taught in Syllabus',
      matched_industry_skill: 'GraphQL APIs & Asynchronous Messaging (Kafka / Redis)',
      similarity: 18.0,
      priority: 'MEDIUM',
      status: 'GAP',
      category: 'Software Engineering',
      industry_demand_score: 84,
      industry_importance_score: 80,
      trend: 'STABLE',
      academic_evidence: 'Only REST API basics are discussed; missing event-driven architecture and GraphQL schema design.',
      industry_evidence: 'Widely adopted in high-scale distributed systems and microservices.',
    },
  ],
  priority_summary: {
    CRITICAL: 2,
    HIGH: 3,
    MEDIUM: 2,
    LOW: 4,
    total_gaps: 7,
  },
  recommendations: [
    {
      id: 'rec-1',
      technology: 'Docker & Kubernetes Cloud Containerization',
      category: 'DevOps & Cloud Infrastructure',
      priority: 'CRITICAL',
      reason: 'Critical gap between theoretical Operating Systems course and modern cloud deployment standards.',
      industry_evidence: 'Docker & Kubernetes appear in 89% of backend developer job listings in Q1 2026.',
      suggested_course: 'CS110+ Cloud Native Systems Module',
      suggested_module: 'Module 5: Microservices Containerization with Docker & Podman',
      learning_outcomes: [
        'Containerize multi-container web apps using Docker Compose',
        'Deploy and auto-scale applications on Kubernetes clusters using Helm',
        'Configure ingress controllers, secrets, and persistent volumes',
      ],
      hands_on_lab: 'Build a multi-container Dockerized microservices stack with PostgreSQL and Redis',
      mini_project: 'Deploy a resilient Kubernetes cluster hosting a distributed web application on GCP/AWS',
      estimated_hours: 24,
      difficulty: 'Intermediate',
      references: ['https://kubernetes.io/docs/', 'https://docs.docker.com/'],
    },
    {
      id: 'rec-2',
      technology: 'Generative AI, RAG & Vector Search (Pinecone/Qdrant)',
      category: 'AI & Data Science',
      priority: 'CRITICAL',
      reason: 'Academic CS229 covers traditional ML but lacks generative AI, LLM orchestration, and RAG pipelines.',
      industry_evidence: 'AI Engineer roles grew 340% YoY; RAG and vector embeddings are key prerequisites.',
      suggested_course: 'CS229+ Applied Generative AI Systems',
      suggested_module: 'Module 4: Enterprise RAG Architecture & Vector Indexing',
      learning_outcomes: [
        'Generate dense text embeddings using state-of-the-art transformer models',
        'Store and query high-dimensional vectors in Pinecone/Qdrant databases',
        'Build end-to-end RAG question-answering systems with citations and hallucination guards',
      ],
      hands_on_lab: 'Implement a semantic document retriever using LangChain and Pinecone vector store',
      mini_project: 'Develop an enterprise AI knowledge assistant for academic research papers',
      estimated_hours: 30,
      difficulty: 'Advanced',
      references: ['https://docs.pinecone.io/', 'https://python.langchain.com/'],
    },
    {
      id: 'rec-3',
      technology: 'Infrastructure as Code (Terraform) & CI/CD Pipelines',
      category: 'DevOps & Infrastructure',
      priority: 'HIGH',
      reason: 'Manual software deployment is obsolete; industry requires automated GitOps workflows.',
      industry_evidence: '82% of DevOps positions list Terraform and GitHub Actions as mandatory skills.',
      suggested_course: 'CS144+ Modern Cloud Operations',
      suggested_module: 'Module 3: GitOps Automation with GitHub Actions & Terraform',
      learning_outcomes: [
        'Provision cloud infrastructure declaratively using HCL Terraform',
        'Construct automated CI/CD build, test, and release pipelines',
      ],
      hands_on_lab: 'Create a GitHub Action workflow to automatically test and deploy Docker containers on push',
      mini_project: 'Automated terraform script provisioning AWS ECS cluster with SSL certificates',
      estimated_hours: 18,
      difficulty: 'Intermediate',
      references: ['https://developer.hashicorp.com/terraform/docs'],
    },
  ],
  learning_paths: {
    target_role: 'Full-Stack Cloud & AI Software Architect',
    total_semesters: 4,
    roadmap: [
      {
        semester: 'Semester 1',
        title: 'Foundational Systems & Modern Web Stack',
        description: 'Bridge traditional core CS with modern React 19, TypeScript, and Docker containerization fundamentals.',
        prerequisites: ['Data Structures', 'Basic Programming'],
        skills_acquired: ['React 19', 'TypeScript', 'Docker Basics', 'REST & OpenAPI'],
        estimated_weeks: 12,
        capstone_project: 'Full-stack TypeScript Task Orchestrator containerized with Docker',
      },
      {
        semester: 'Semester 2',
        title: 'Cloud Native Microservices & Kubernetes',
        description: 'Master distributed systems, Kubernetes cluster management, gRPC, and asynchronous event streaming.',
        prerequisites: ['Semester 1 Stack', 'Operating Systems'],
        skills_acquired: ['Kubernetes', 'Helm', 'gRPC', 'Redis Caching', 'Apache Kafka'],
        estimated_weeks: 14,
        capstone_project: 'Resilient Microservices Streaming Engine deployed on Kubernetes',
      },
      {
        semester: 'Semester 3',
        title: 'Applied Generative AI & Vector Search Engine',
        description: 'Integrate LLMs, multi-agent frameworks, vector vector DBs, and RAG architectures.',
        prerequisites: ['Machine Learning Basics', 'Python'],
        skills_acquired: ['Gemini 1.5 Pro API', 'Pinecone', 'LangChain', 'RAG Pipelines'],
        estimated_weeks: 14,
        capstone_project: 'Enterprise RAG Agent for Automated Code Auditing',
      },
      {
        semester: 'Semester 4',
        title: 'DevOps Automation, Security & Senior Capstone',
        description: 'Implement Terraform IaC, zero-trust security rules, and production deployment pipeline.',
        prerequisites: ['Semesters 1-3'],
        skills_acquired: ['Terraform', 'GitHub Actions', 'OAuth2 / JWT', 'Prometheus Monitoring'],
        estimated_weeks: 16,
        capstone_project: 'Autonomous AI SaaS Platform with 99.9% Uptime SLA',
      },
    ],
  },
  industry_statistics: {
    top_demanded_skills: [
      { name: 'Docker & Containers', score: 98 },
      { name: 'Kubernetes', score: 95 },
      { name: 'Vector Search / RAG', score: 96 },
      { name: 'React 19 & TypeScript', score: 94 },
      { name: 'Python & FastApi', score: 92 },
      { name: 'Terraform IaC', score: 90 },
      { name: 'PostgreSQL & Redis', score: 89 },
    ],
    trending_technologies: [
      { name: 'RAG & Vector Databases', growth: 340, category: 'AI & Machine Learning' },
      { name: 'Kubernetes & Service Mesh', growth: 185, category: 'Cloud Infrastructure' },
      { name: 'TypeScript & Next.js 15', growth: 140, category: 'Web Development' },
      { name: 'Terraform & OpenTofu', growth: 120, category: 'DevOps & IaC' },
      { name: 'Rust Systems Programming', growth: 210, category: 'Systems Programming' },
    ],
    emerging_skills: [
      { name: 'AI Agent Frameworks (LangGraph/AGY)', score: 99 },
      { name: 'WebAssembly (Wasm)', score: 88 },
      { name: 'Zero-Trust Cloud Security', score: 92 },
    ],
    category_distribution: {
      'AI & Data Science': 35,
      'DevOps & Cloud': 28,
      'Web & Mobile Development': 20,
      'Software Architecture': 12,
      'Cybersecurity': 5,
    },
  },
  academic_statistics: {
    total_courses: 24,
    total_skills_extracted: 142,
    top_categories: {
      'Computer Science Core': 45,
      'Mathematics & Theory': 25,
      'Systems Programming': 20,
      'Web Technologies': 10,
    },
  },
  processing_metrics: {
    extraction_time_ms: 420,
    semantic_match_time_ms: 680,
    recommendation_time_ms: 540,
  },
  execution_time: 1.64,
  generated_at: new Date().toISOString(),
  warnings_or_errors: [],
};

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  total_analyses_conducted: 38,
  avg_alignment_score: 74.5,
  total_skills_mapped: 1240,
  system_health_status: 'OPERATIONAL',
  cache_hit_ratio: 0.942,
  top_industry_gaps: ['Docker', 'Kubernetes', 'RAG & Vector DBs', 'Terraform IaC', 'TypeScript'],
  active_workflows_count: 0,
};

export const MOCK_STATUS_SUMMARY: StatusSummary = {
  status: 'OPERATIONAL',
  uptime_seconds: 142500,
  active_jobs_count: 0,
  active_jobs: [],
};

export const MOCK_HEALTH_CHECK: HealthCheckResult = {
  status: 'HEALTHY',
  components: {
    academic_engine: { status: 'HEALTHY', latency_ms: 12, message: 'PDF Extraction Engine operational.' },
    industry_engine: { status: 'HEALTHY', latency_ms: 18, message: 'Neo4j Knowledge Graph connected.' },
    semantic_engine: { status: 'HEALTHY', latency_ms: 25, message: 'Pinecone Vector DB & Gemini embeddings active.' },
    recommendation_engine: { status: 'HEALTHY', latency_ms: 32, message: 'Gemini 1.5 Pro LLM client online.' },
    redis_cache: { status: 'HEALTHY', latency_ms: 3, message: 'Redis cache hit ratio 94.2%.' },
  },
  checked_at: new Date().toISOString(),
};

export const MOCK_KNOWLEDGE_GRAPH: KnowledgeGraphData = {
  nodes: [
    { id: 'node-cs106b', label: 'CS106B: Programming Abstractions', type: 'course', category: 'Core Course' },
    { id: 'node-cs110', label: 'CS110: Principles of Computer Systems', type: 'course', category: 'Systems' },
    { id: 'node-cs229', label: 'CS229: Machine Learning', type: 'course', category: 'AI/ML' },
    { id: 'node-dsa', label: 'Data Structures & Algorithms', type: 'academic_skill', category: 'Core Skill' },
    { id: 'node-os', label: 'Operating Systems & Concurrency', type: 'academic_skill', category: 'Systems' },
    { id: 'node-ml-basic', label: 'Supervised ML Algorithms', type: 'academic_skill', category: 'AI/ML' },
    { id: 'node-docker', label: 'Docker & Kubernetes', type: 'gap', category: 'DevOps Delta' },
    { id: 'node-rag', label: 'Vector DBs & RAG Architecture', type: 'gap', category: 'AI Delta' },
    { id: 'node-industry-devops', label: 'Senior Cloud Engineer', type: 'industry_skill', category: 'Target Role' },
    { id: 'node-industry-ai', label: 'AI Platform Engineer', type: 'industry_skill', category: 'Target Role' },
  ],
  edges: [
    { id: 'e1', source: 'node-cs106b', target: 'node-dsa', label: 'teaches' },
    { id: 'e2', source: 'node-cs110', target: 'node-os', label: 'teaches' },
    { id: 'e3', source: 'node-cs229', target: 'node-ml-basic', label: 'teaches' },
    { id: 'e4', source: 'node-os', target: 'node-docker', label: 'prerequisite gap' },
    { id: 'e5', source: 'node-ml-basic', target: 'node-rag', label: 'prerequisite gap' },
    { id: 'e6', source: 'node-docker', target: 'node-industry-devops', label: 'required for' },
    { id: 'e7', source: 'node-rag', target: 'node-industry-ai', label: 'required for' },
  ],
};
